### ISSUE TITLE
Tests fail with 'Mokito cannot mock this class'  

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/rsp-server#148]
``` junit

testCannotRemoveDeployable(org.jboss.tools.rsp.server.model.ServerDeployableTest)  Time elapsed: 0.023 sec  <<< ERROR!
org.mockito.exceptions.base.MockitoException: 

Mockito cannot mock this class: class org.jboss.tools.rsp.server.model.ServerDeployableTest$TestServerDelegate.
Most likely it is a private class that is not visible by Mockito
	at org.jboss.tools.rsp.server.model.ServerDeployableTest.lambda$2(ServerDeployableTest.java:116)
	at org.jboss.tools.rsp.server.model.ServerDeployableTest.createServerModel(ServerDeployableTest.java:487)
	at org.jboss.tools.rsp.server.model.ServerDeployableTest.testCannotRemoveDeployable(ServerDeployableTest.java:114)

testCannotRemoveInexistantDeployable(org.jboss.tools.rsp.server.model.ServerDeployableTest) skipped
testDefaultPublishImplementationWithDelay(org.jboss.tools.rsp.server.model.ServerDeployableTest)  Time elapsed: 0.012 sec
testCannotAddDeployable(org.jboss.tools.rsp.server.model.ServerDeployableTest)  Time elapsed: 0.015 sec  <<< ERROR!
org.mockito.exceptions.base.MockitoException: 

Mockito cannot mock this class: class org.jboss.tools.rsp.server.model.ServerDeployableTest$TestServerDelegate.
Most likely it is a private class that is not visible by Mockito
	at org.jboss.tools.rsp.server.model.ServerDeployableTest.lambda$1(ServerDeployableTest.java:97)
	at org.jboss.tools.rsp.server.model.ServerDeployableTest.createServerModel(ServerDeployableTest.java:487)
	at org.jboss.tools.rsp.server.model.ServerDeployableTest.testCannotAddDeployable(ServerDeployableTest.java:95)
```

**Comment by dgolovin** [comment]
@robstryker Is there any reason to keep that class private?

**Comment by adietish** [comment]
@dgolovin this is/was occurring in the robstryker/publishing branch, correct? that was fixed in the meantime, look here: https://github.com/robstryker/rsp-server/blob/publishing/framework/tests/org.jboss.tools.rsp.server.test/src/main/java/org/jboss/tools/rsp/server/model/ServerDeployableTest.java#L459

```
public class TestServerDelegate extends AbstractServerDelegate {
```

Resolving.
