### ISSUE TITLE
make sure rsp-server works with Java 11

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#184]
rsp-server doesn't work with java 11 currently. We should fix this even more given that java support for vscode was fixed to support java 11: https://github.com/redhat-developer/vscode-java/issues/625

**Comment by adietish** [comment]
java 11 is only supported via tycho 1.3 which is currently only available as 1.3.0-SNAPSHOT:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=532302

**Comment by adietish** [comment]
using tycho 1.3.0-SNAPSHOT compiling works fine, but launching tests fails while there's no log at the location that's indicated:
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:1.3.0-SNAPSHOT:test (default-test) on project org.jboss.tools.rsp.launching.test: An unexpected error occured while launching the test runtime (return code 13). See log /Users/adietish/Documents/jboss-workspaces/rsp-server/framework/tests/org.jboss.tools.rsp.launching.test/target/work/data/.metadata/.log for details. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:1.3.0-SNAPSHOT:test (default-test) on project org.jboss.tools.rsp.launching.test: An unexpected error occured while launching the test runtime (return code 13)
```

**Comment by jeffmaury** [comment]
You need to pass spécial arguments related to the module. Check jbosstools parent for inspiration

**Comment by adietish** [comment]
@jeffmaury thx good hint. So I added ```--add-modules=ALL-SYSTEM``` but things unfortunately still dont work. I now see the following error in the log:
```
!ENTRY org.eclipse.tycho.surefire.junit4 2 0 2018-12-13 16:47:17.360
!MESSAGE Could not resolve module: org.eclipse.tycho.surefire.junit4 [16]
  Unresolved requirement: Import-Package: javax.annotation


!ENTRY org.eclipse.osgi 4 0 2018-12-13 16:47:17.363
!MESSAGE Application error
!STACK 1
org.apache.maven.surefire.util.SurefireReflectionException: java.lang.ClassNotFoundException: org.apache.maven.surefire.junit4.JUnit4Provider
        at org.apache.maven.surefire.util.ReflectionUtils.loadClass(ReflectionUtils.java:249)
        at org.apache.maven.surefire.util.ReflectionUtils.instantiateOneArg(ReflectionUtils.java:133)
        at org.apache.maven.surefire.booter.SurefireReflector.instantiateProvider(SurefireReflector.java:265)
        at org.apache.maven.surefire.booter.ProviderFactory.createProvider(ProviderFactory.java:118)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:83)
        at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:110)
        at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.run(HeadlessTestApplication.java:21)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:590)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:201)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
Caused by: java.lang.ClassNotFoundException: org.apache.maven.surefire.junit4.JUnit4Provider
        at org.eclipse.tycho.surefire.osgibooter.CombinedClassLoader.findClass(CombinedClassLoader.java:37)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.apache.maven.surefire.util.ReflectionUtils.loadClass(ReflectionUtils.java:241)
```

**Comment by adietish** [comment]
Remaining task of updating the jenkinsfile to run tests in jdk8 and jdk11 was filed to #195.
PR was merged. Resolving & Closing.
