### ISSUE TITLE
Download runtime calls fail due to bad bundle packaging

### ISSUE THREAD

**Issue by robstryker** [redhat-developer/rsp-server#242]
bundle/org.jboss.tools.rsp.stacks.core_0.13.1.Final.jar has no bundled libs. 

This causes critical error when calling download-runtime APIs. 

java.lang.NoClassDefFoundError: org/jboss/jdf/stacks/client/messages/StacksMessages

	at org.jboss.tools.rsp.server.wildfly.runtimes.download.DownloadRuntimesProvider.getStacks(DownloadRuntimesProvider.java:66)
	at org.jboss.tools.rsp.server.spi.runtimes.AbstractStacksDownloadRuntimesProvider.loadDownloadableRuntimes(AbstractStacksDownloadRuntimesProvider.java:80)
	at org.jboss.tools.rsp.server.spi.runtimes.AbstractStacksDownloadRuntimesProvider.getDownloadableRuntimes(AbstractStacksDownloadRuntimesProvider.java:51)
	at org.jboss.tools.rsp.runtime.core.model.internal.DownloadRuntimesModel.cacheDownloadRuntimes(DownloadRuntimesModel.java:127)
	at org.jboss.tools.rsp.runtime.core.model.internal.DownloadRuntimesModel.ensureCacheLoaded(DownloadRuntimesModel.java:66)
	at org.jboss.tools.rsp.runtime.core.model.internal.DownloadRuntimesModel.getOrLoadDownloadRuntimes(DownloadRuntimesModel.java:59)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.listDownloadableRuntimesInternal(ServerManagementServerImpl.java:589)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.lambda$24(ServerManagementServerImpl.java:585)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.lambda$23(ServerManagementServerImpl.java:577)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: org.jboss.jdf.stacks.client.messages.StacksMessages not found by org.jboss.tools.rsp.stacks.core [22]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1597)
	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more

**Comment by robstryker** [comment]
* 8c93a7a - [242] Bad stacks bundle packaging (12 minutes ago) <Rob Stryker>
