### ISSUE TITLE
stackoverflow when stopping the server

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#256]
```
Exception in thread "wf15 - Server Poller" 
java.lang.StackOverflowError


	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.<init>(Executors.java:684)

	at java.base/java.util.concurrent.Executors$FinalizableDelegatedExecutorService.<init>(Executors.java:758)

	at java.base/java.util.concurrent.Executors.newSingleThreadExecutor(Executors.java:194)
	at org.jboss.tools.rsp.server.spi.model.polling.AbstractPoller.<init>(AbstractPoller.java:28)

	at org.jboss.tools.rsp.server.spi.model.polling.WebPortPoller.<init>(WebPortPoller.java:25)

	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate$1.<init>(AbstractJBossServerDelegate.java:169)

	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.getDefaultWebPortPoller(AbstractJBossServerDelegate.java:169)

	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.getPoller(AbstractJBossServerDelegate.java:165)

	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.launchPoller(AbstractJBossServerDelegate.java:157)

	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.stop(AbstractJBossServerDelegate.java:131)

	at org.jboss.tools.rsp.server.model.AbstractServerDelegate$1.stateNotAsserted(AbstractServerDelegate.java:354)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.alertListener(PollThread.java:193)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.cancel(PollThread.java:171)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.cancel(PollThread.java:164)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.cancelPolling(PollThreadUtils.java:51)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.stopPolling(PollThreadUtils.java:34)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:95)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:73)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:66)

	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.launchPoller(AbstractJBossServerDelegate.java:158)

	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.stop(AbstractJBossServerDelegate.java:131)

	at org.jboss.tools.rsp.server.model.AbstractServerDelegate$1.stateNotAsserted(AbstractServerDelegate.java:354)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.alertListener(PollThread.java:193)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.cancel(PollThread.java:171)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.cancel(PollThread.java:164)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.cancelPolling(PollThreadUtils.java:51)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.stopPolling(PollThreadUtils.java:34)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:95)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:73)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:66)

	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.launchPoller(AbstractJBossServerDelegate.java:158)

	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.stop(AbstractJBossServerDelegate.java:131)

	at org.jboss.tools.rsp.server.model.AbstractServerDelegate$1.stateNotAsserted(AbstractServerDelegate.java:354)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.alertListener(PollThread.java:193)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.cancel(PollThread.java:171)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.cancel(PollThread.java:164)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.cancelPolling(PollThreadUtils.java:51)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.stopPolling(PollThreadUtils.java:34)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:95)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:73)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:66)
	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.launchPoller(AbstractJBossServerDelegate.java:158)

	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.stop(AbstractJBossServerDelegate.java:131)

	at org.jboss.tools.rsp.server.model.AbstractServerDelegate$1.stateNotAsserted(AbstractServerDelegate.java:354)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.alertListener(PollThread.java:193)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.cancel(PollThread.java:171)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.cancel(PollThread.java:164)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.cancelPolling(PollThreadUtils.java:51)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.stopPolling(PollThreadUtils.java:34)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:95)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:73)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:66)

	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.launchPoller(AbstractJBossServerDelegate.java:158)
	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.stop(AbstractJBossServerDelegate.java:131)

	at org.jboss.tools.rsp.server.model.AbstractServerDelegate$1.stateNotAsserted(AbstractServerDelegate.java:354)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.alertListener(PollThread.java:193)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.cancel(PollThread.java:171)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.cancel(PollThread.java:164)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.cancelPolling(PollThreadUtils.java:51)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.stopPolling(PollThreadUtils.java:34)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:95)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:73)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:66)
	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.launchPoller(AbstractJBossServerDelegate.java:158)
	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.stop(AbstractJBossServerDelegate.java:131)

	at org.jboss.tools.rsp.server.model.AbstractServerDelegate$1.stateNotAsserted(AbstractServerDelegate.java:354)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.alertListener(PollThread.java:193)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.cancel(PollThread.java:171)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThread.cancel(PollThread.java:164)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.cancelPolling(PollThreadUtils.java:51)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.stopPolling(PollThreadUtils.java:34)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:95)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:73)

	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.pollServer(PollThreadUtils.java:66)
	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.launchPoller(AbstractJBossServerDelegate.java:158)

	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.stop(AbstractJBossServerDelegate.java:131)
```

**Comment by robstryker** [comment]
Fixed https://github.com/redhat-developer/rsp-server/pull/257
