### ISSUE TITLE
cannot launch wildfly 15 using jdk11

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#258]
Even though wildfly 15 officially supports jdk11, we cannot launch it in rsp-server. 
The reason is that we're not using the launch script but our own cmd-line.

related to #215

**Comment by odockal** [comment]
I would like to add possible cause that should help investigating the root cause. When starting the server (wf15) via cmd and with use of felix server and client, I got this error:
```
Server state change: 
  Server:org.jboss.tools.rsp.api.dao.ServerType@17c2afc3:wildfly-15
  State: starting
  Publish State: unknown
  Deployments: 
Server process created: org.jboss.tools.rsp.api.dao.ServerType@17c2afc3:wildfly-15 @ org.jboss.ide.eclipse.as.wildfly.150:wildfly-15:1553074415396:p0
Status OK: unknown code=0 ok null
ServerOutput: org.jboss.tools.rsp.api.dao.ServerType@17c2afc3:wildfly-15 [org.jboss.ide.eclipse.as.wildfly.150:wildfly-15:1553074415396:p0][1] org.jboss.modules.ModuleNotFoundException: java.se

ServerOutput: org.jboss.tools.rsp.api.dao.ServerType@17c2afc3:wildfly-15 [org.jboss.ide.eclipse.as.wildfly.150:wildfly-15:1553074415396:p0][1] 	at org.jboss.modules.Module.addPaths(Module.java:1266)
	at org.jboss.modules.Module.link(Module.java:1622)
	at org.jboss.modules.Module.relinkIfNecessary(Module.java:1650)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:296)
	at org.jboss.modules.Main.main(Main.java:437)

Server state change: 
  Server:org.jboss.tools.rsp.api.dao.ServerType@17c2afc3:wildfly-15
  State: stopped
  Publish State: unknown
  Deployments: 
Server process terminated: org.jboss.tools.rsp.api.dao.ServerType@17c2afc3:wildfly-15 @ org.jboss.ide.eclipse.as.wildfly.150:wildfly-15:1553074415396:p0
```

**Comment by robstryker** [comment]
https://github.com/jbosstools/jbosstools-server/commit/f77aa1b6a63c25329c1e383bfb8e4f94e59dd97f#diff-c9c1abd0b2729e5a4723f9a5faf5942eR30

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/278  Fixed
