### ISSUE TITLE
Unit tests persist garbage data

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/rsp-server#33]
Running the tests leaves data in home/.org.jboss.tools.rsp.data. So after building the project and running the felix jar you get greeted by

```
java.lang.Exception: Unable to load server from file /home/jrichter/.org.jboss.tools.rsp.data/servers/test.name1; server type test1 is not found in model.
	at org.jboss.tools.rsp.server.model.ServerModel.loadServers(ServerModel.java:130)
	at org.jboss.tools.rsp.server.model.ServerModel.loadServers(ServerModel.java:106)
	at org.jboss.tools.rsp.server.model.ServerPersistenceManager.loadState(ServerPersistenceManager.java:89)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.launch(ServerManagementServerLauncher.java:67)
	at org.jboss.tools.rsp.server.ServerCoreActivator$1.run(ServerCoreActivator.java:58)

```

**Comment by robstryker** [comment]
* 6c782e0 - (HEAD -> master, origin/master, origin/HEAD) Issue 33 - part deux, makes sure all data is done in temporary locations (2 minutes ago) <Rob Stryker>
* f8f2bdd - Issue 33 - part 1, clean up folder where fake runtimes are created (23 minutes ago) <Rob Stryker>
