### ISSUE TITLE
Cancelling a runtime download leaves the folder

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-server#360]
I started a runtime download then cancelled it and notice the folder under `runtimes` is still present

**Comment by adietish** [comment]
+1, we should clean it up

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/363

**Comment by adietish** [comment]
I can't confirm that cancelled downloads are removed.

steps:
1. EXEC: launch server & cli
1. EXEC: start downloading a runtime
1. ASSERT: download job is running
1. EXEC: in cli: "cancel job"
1. ASSERT: get prompted to select a job
1. EXEC: select your job

Result:
```
Job Download runtime: WildFly 15.0.1 Final (f0af2d4d-b908-4c15-8b8d-7b3c36979ba4) has stopped running: Status ERROR: org.jboss.tools.rsp.runtime.core code=0 Error while retrieving runtime from http://download.jboss.org/wildfly/15.0.1.Final/wildfly-15.0.1.Final.zip org.jboss.tools.rsp.eclipse.core.runtime.CoreException: 
	at org.jboss.tools.rsp.runtime.core.util.internal.DownloadRuntimeOperationUtility.downloadRemoteRuntime(DownloadRuntimeOperationUtility.java:188)
	at org.jboss.tools.rsp.runtime.core.util.internal.DownloadRuntimeOperationUtility.downloadAndUnzip(DownloadRuntimeOperationUtility.java:152)
	at org.jboss.tools.rsp.runtime.core.model.installer.internal.ExtractionRuntimeInstaller.installRuntime(ExtractionRuntimeInstaller.java:40)
	at org.jboss.tools.rsp.server.spi.runtimes.AbstractLicenseOnlyDownloadExecutor$1.run(AbstractLicenseOnlyDownloadExecutor.java:149)
	at org.jboss.tools.rsp.server.spi.jobs.SimpleJob.run(SimpleJob.java:96)
	at org.jboss.tools.rsp.server.jobs.JobManager.lambda$0(JobManager.java:86)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.AsynchronousCloseException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:205)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:387)
	at org.jboss.tools.rsp.foundation.core.transport.CallbackByteChannel.read(CallbackByteChannel.java:52)
	at sun.nio.ch.FileChannelImpl.transferFromArbitraryChannel(FileChannelImpl.java:673)
	at sun.nio.ch.FileChannelImpl.transferFrom(FileChannelImpl.java:711)
	at org.jboss.tools.rsp.foundation.core.transport.URLTransportCache.download(URLTransportCache.java:413)
	at org.jboss.tools.rsp.foundation.core.transport.URLTransportCache.download(URLTransportCache.java:376)
	at org.jboss.tools.rsp.runtime.core.util.internal.DownloadRuntimeOperationUtility.downloadFileFromRemoteUrl(DownloadRuntimeOperationUtility.java:250)
	at org.jboss.tools.rsp.runtime.core.util.internal.DownloadRuntimeOperationUtility.downloadRemoteRuntime(DownloadRuntimeOperationUtility.java:185)
	... 8 more
```
Partial zip file is still present in ```~/.org.jboss.tools.rsp.data/runtimes/downloads/```

**Comment by adietish** [comment]
@robstryker I'd suggest to add unit tests for at least ```DownloadRuntimeOperationUtility```.

**Comment by robstryker** [comment]
@adietish  your line numbers match the following commit:
 * cf62e936 - (HEAD) Alphanumeric comparator has a bug (6 days ago) <Rob Stryker>

Unfortunately the commit log looks like this:
* 58732531 - (HEAD -> master, origin/master, origin/HEAD) Small cleanup; dlrt map should not be initialized right away (3 days ago) <Rob Stryker>
* 84e978e4 - [361] Improve add-deployment rejection message (6 days ago) <Rob Stryker>
* 5457895e - [360] Also fix for CDK (6 days ago) <Rob Stryker>
* c1e98a56 - [360] Cleanup after canceled download (6 days ago) <Rob Stryker>
* cf62e936 - Alphanumeric comparator has a bug (6 days ago) <Rob Stryker>

I think your tests were done without updatign to master to receive the two commits that fix issue 360.

**Comment by adietish** [comment]
@robstryker i thought to have used the latest version of the server, manually building and deploying it to vscode. I'll verify it again.

**Comment by adietish** [comment]
Tested it again. Now the exception that is thrown is different:
```
Job Download runtime: WildFly 15.0.1 Final (52867ec3-16df-4cf0-9d20-081a2c26d168) has stopped running: Status CANCEL: org.jboss.tools.rsp.runtime.core code=0 Error while retrieving runtime from http://download.jboss.org/wildfly/15.0.1.Final/wildfly-15.0.1.Final.zip org.jboss.tools.rsp.eclipse.core.runtime.CoreException: 
	at org.jboss.tools.rsp.runtime.core.util.internal.DownloadRuntimeOperationUtility.downloadRemoteRuntime(DownloadRuntimeOperationUtility.java:199)
	at org.jboss.tools.rsp.runtime.core.util.internal.DownloadRuntimeOperationUtility.downloadAndUnzip(DownloadRuntimeOperationUtility.java:156)
	at org.jboss.tools.rsp.runtime.core.model.installer.internal.ExtractionRuntimeInstaller.installRuntime(ExtractionRuntimeInstaller.java:40)
	at org.jboss.tools.rsp.server.spi.runtimes.AbstractLicenseOnlyDownloadExecutor$1.run(AbstractLicenseOnlyDownloadExecutor.java:150)
	at org.jboss.tools.rsp.server.spi.jobs.SimpleJob.run(SimpleJob.java:96)
	at org.jboss.tools.rsp.server.jobs.JobManager.lambda$0(JobManager.java:86)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
and the partial download is not present any more, things were cleaned up. 
Resolving given that I can now confirm that this is fixed. Sorry for the confusion.
