### ISSUE TITLE
NPE when downloading credentialed runtime after server restart

### ISSUE THREAD

**Issue by robstryker** [redhat-developer/rsp-server#436]
Steps to reproduce:
  1) Start rsp-server (cli or vscode)
  2) download a runtime like eap 7.2 or cdk
  3) provide credentials (both secure storage and rht credentials)
  4) Once completed, shut down rsp-server
  5) restart rsp-server
  6) try to download another credentialed runtime (eap 7.1 or other version cdk)
  7) Server fails to respond in any real way, seems to ignore request

java.lang.NullPointerException
	at java.lang.reflect.Proxy.getInvocationHandler(Proxy.java:815)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:99)
	at com.sun.proxy.$Proxy4.equals(Unknown Source)
	at java.util.ArrayList.indexOf(ArrayList.java:321)
	at java.util.ArrayList.contains(ArrayList.java:304)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.getSecureStorage(SecureStorageGuardian.java:134)

Unfortunately this issue is difficult to test. A test I have written passes even in the failing code. This has to do with mockito's method of stubbing the .equals method. While there is an issue here in rsp-server where we add a 'null' item to a list, which can fix the issue, the root cause of this specific NPE is in the lsp4j proxy class, which does not check that the argument is null or not and causes an NPE. 

Trying to test this is proving impossible due to the way mockito is working. I will submit patches for both rsp-server and lsp4j.

**Comment by robstryker** [comment]
I also opened https://github.com/eclipse/lsp4j/pull/339   to fix part of the underlying issue.

**Comment by robstryker** [comment]
Fix here:  https://github.com/redhat-developer/rsp-server/pull/437

**Comment by robstryker** [comment]
Related to https://github.com/redhat-developer/vscode-rsp-ui/issues/37#issuecomment-514538972

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/437  pushed to master
