### ISSUE TITLE
Error after updating extensions

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/rsp-server#491]
After updating the extensions, rsp-server wasn't able to start. It displayed this error

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.io.UncheckedIOException: java.nio.file.AccessDeniedException: /home/luca/.org.jboss.tools.rsp.data/runtimes/installations/crc1000/crc-linux-1.0.0-beta.5-amd64/openshift.local.clusterup/openshift.local.volumes/pods
    at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:88)
    at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
    at java.util.Iterator.forEachRemaining(Iterator.java:115)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at org.jboss.tools.rsp.server.persistence.DataLocationCore.copyFolder(DataLocationCore.java:88)
    at org.jboss.tools.rsp.server.persistence.DataLocationCore.checkUpdateWorkspace(DataLocationCore.java:67)
    at org.jboss.tools.rsp.server.persistence.DataLocationCore.<init>(DataLocationCore.java:39)
    at org.jboss.tools.rsp.server.persistence.DataLocationCore.<init>(DataLocationCore.java:34)
    at org.jboss.tools.rsp.server.model.ServerManagementModel.<init>(ServerManagementModel.java:68)
    at org.jboss.tools.rsp.server.ServerManagementServerLauncher.createImpl(ServerManagementServerLauncher.java:55)
    at org.jboss.tools.rsp.server.ServerManagementServerLauncher.<init>(ServerManagementServerLauncher.java:50)
    at org.jboss.tools.rsp.server.ServerCoreActivator.startServer(ServerCoreActivator.java:40)
    at org.jboss.tools.rsp.server.ServerCoreActivator.start(ServerCoreActivator.java:26)
    at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
    at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
    at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
    at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
    at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.AccessDeniedException: /home/luca/.org.jboss.tools.rsp.data/runtimes/installations/crc1000/crc-linux-1.0.0-beta.5-amd64/openshift.local.clusterup/openshift.local.volumes/pods
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427)
    at java.nio.file.Files.newDirectoryStream(Files.java:457)
    at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300)
    at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
    at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:84)
    ... 24 more
```

To solve this i had to remove crc manually from .../.org.jboss.tools.rsp.data/runtimes/installations
After the removal everything worked perfectly as before. I'm also able to create a new crc server now. If you had a crc server set up before the updating, you should see this error as well. BTW this shouldn't affect any user as crc wasn't available before.

**Comment by robstryker** [comment]
I think this should be fixed

**Comment by robstryker** [comment]
Oops:  https://github.com/redhat-developer/rsp-server/pull/493
