### ISSUE TITLE
ArrayStoreException launched when a new server is defined

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-server#50]
Steps: 
1) EXEC: in Eclipse: launch ```org.jboss.tools.rsp.server.wildfly.impl.WildflyServerMain```, in arguments use 275111
2) EXEC: launch VSCode, activate "Servers" view (to activate the extension)
3) ASSERT: in VSCode: have an error message in "OUTPUT":  ```[1] 1537519431756: Unable to launch RSP server````
4) EXEC: in VSCode: add a server pointing it to a wildfly distro (ex. wfl-14)

Result:
In Eclipse you'll see the following stacktrace:
```
sept. 21, 2018 9:50:50 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
GRAVE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:116)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:257)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:186)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.lambda$wrapMessageConsumer$0(Launcher.java:308)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
	... 12 more
Caused by: java.lang.ArrayStoreException: [Lorg.jboss.tools.rsp.server.spi.discovery.ServerBeanType;
	at java.util.stream.Nodes$FixedNodeBuilder.accept(Nodes.java:1222)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at org.jboss.tools.rsp.server.discovery.serverbeans.ServerBeanTypeManager.getAllRegisteredTypes(ServerBeanTypeManager.java:33)
	at org.jboss.tools.rsp.server.discovery.serverbeans.ServerBeanLoader.loadTypeInternal(ServerBeanLoader.java:52)
	at org.jboss.tools.rsp.server.discovery.serverbeans.ServerBeanLoader.loadBeanInternal(ServerBeanLoader.java:47)
	at org.jboss.tools.rsp.server.discovery.serverbeans.ServerBeanLoader.getServerBean(ServerBeanLoader.java:35)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.findServerBeans(ServerManagementServerImpl.java:214)
	... 17 more



```

**Comment by adietish** [comment]
fixed by https://github.com/redhat-developer/rsp-server/issues/50. Resolving.
