### ISSUE TITLE
Server launches before extension bundles are started

### ISSUE THREAD

**Issue by robstryker** [redhat-developer/rsp-server#529]
There's a very clear race condition occuring on occasion. The bundle
org.jboss.tools.rsp.server.ServerCoreActivator, in its start method, launches a new thread which will start the server and begin listening for connections. 

Other bundles (wfly, minishift, tomcat, karaf, etc) depend on this bundle and, via api, add their extensions to the framework. 

The org.jboss.tools.rsp.server bundle will attempt to read the workspace for previously-declared servers. If it attempts to read a file (say a karaf runtime) before the karaf bundle has added its extensions, it will fail. 

```

16:24:42.036 [unch RSP Server] ERROR o.j.t.rsp.server.model.ServerModel:216 - Unable to load server from file /home/odockal/.rsp/redhat-server-connector-community/servers/apache-karaf-4.2.8; server type org.jboss.ide.eclipse.as.server.karaf.42 is not found in model.
java.lang.Exception: Unable to load server from file /home/odockal/.rsp/redhat-server-connector-community/servers/apache-karaf-4.2.8; server type org.jboss.ide.eclipse.as.server.karaf.42 is not found in model.
	at org.jboss.tools.rsp.server.model.ServerModel.loadServer(ServerModel.java:203)
	at org.jboss.tools.rsp.server.model.ServerModel.loadServers(ServerModel.java:178)
	at org.jboss.tools.rsp.server.model.ServerModel.loadServers(ServerModel.java:170)
	at org.jboss.tools.rsp.server.model.ServerPersistenceManager.loadState(ServerPersistenceManager.java:91)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.launch(ServerManagementServerLauncher.java:83)
	at org.jboss.tools.rsp.server.ServerCoreActivator.lambda$0(ServerCoreActivator.java:45)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by robstryker** [comment]
testPR
