### ISSUE TITLE
Error when starting jboss-as-7.1.0

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/rsp-server#548]
Found this while testing rsp-ui.

i just created a new server by downloading jboss-as-7.1.0 and started it.
This is the error printed when i try to start it
```
Exception in thread "main" javax.xml.parsers.FactoryConfigurationError: Provider __redirected.__SAXParserFactory could not be instantiated: java.lang.NullPointerException
	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:204)
	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:152)
	at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:232)
	at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:127)
	at jdk.xml.internal.JdkXmlUtils.getSAXFactory(JdkXmlUtils.java:235)
	at jdk.xml.internal.JdkXmlUtils.<clinit>(JdkXmlUtils.java:78)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.<init>(SchemaParsingConfig.java:319)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.<init>(SchemaParsingConfig.java:254)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.<init>(XSDHandler.java:480)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.<init>(XSDHandler.java:487)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.<init>(XMLSchemaLoader.java:357)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.<init>(XMLSchemaLoader.java:292)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.<init>(XMLSchemaFactory.java:97)
	at javax.xml.validation.SchemaFactoryFinder._newFactory(SchemaFactoryFinder.java:232)
	at javax.xml.validation.SchemaFactoryFinder.newFactory(SchemaFactoryFinder.java:146)
	at javax.xml.validation.SchemaFactory.newInstance(SchemaFactory.java:213)
	at __redirected.__SchemaFactory.<clinit>(__SchemaFactory.java:66)
	at __redirected.__JAXPRedirected.initAll(__JAXPRedirected.java:88)
	at org.jboss.modules.Module$1.run(Module.java:85)
	at org.jboss.modules.Module$1.run(Module.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.modules.Module.<clinit>(Module.java:72)
	at org.jboss.modules.Main.main(Main.java:255)
Caused by: java.lang.NullPointerException
	at __redirected.__RedirectedUtils.loadProvider(__RedirectedUtils.java:94)
	at __redirected.__RedirectedUtils.loadProvider(__RedirectedUtils.java:87)
	at __redirected.__SAXParserFactory.<init>(__SAXParserFactory.java:102)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:192)
	... 22 more
```

**Comment by robstryker** [comment]
jboss as 7.x is not compatible with java8 really.   https://developer.jboss.org/thread/240679

Fixing.
