### ISSUE TITLE
Saving wrong value when editing server json in vscode editor shows unclear Error message

### ISSUE THREAD

**Issue by odockal** [redhat-developer/rsp-server#647]
1. Create server 
2. Edit server
3. assert: Server.json opened in VSCode
4. change vm.install.path to the wrong path, Save
5. Assert: Clear exception message on the output tabs
Acually I get:
```
13:51:31.563 [onPool-worker-5] ERROR o.j.t.r.s.w.s.AbstractJBossServerDelegate:416 - 
org.jboss.tools.rsp.eclipse.core.runtime.CoreException: 
	at org.jboss.tools.rsp.server.spi.launchers.AbstractJavaLauncher.getLaunchCommand(AbstractJavaLauncher.java:72)
	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.updateDependentAttributes(AbstractJBossServerDelegate.java:414)
	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.updateServer(AbstractJBossServerDelegate.java:403)
	at org.jboss.tools.rsp.server.wildfly.servertype.impl.WildFlyServerDelegate.updateServer(WildFlyServerDelegate.java:69)
	at org.jboss.tools.rsp.server.model.ServerModel.updateServer(ServerModel.java:800)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.updateServerSync(ServerManagementServerImpl.java:400)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.lambda$13(ServerManagementServerImpl.java:396)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.lambda$36(ServerManagementServerImpl.java:915)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by odockal** [comment]
![Screenshot_20210506_135407](https://user-images.githubusercontent.com/19164299/117294107-8b35dd80-ae72-11eb-8d62-350c5fc0634e.png)

**Comment by robstryker** [comment]
Um... you changed the location of your VM to a folder that clearly doesn't have a VM.  Is showing an error in the output here really hte wrong thing to do? Seems appropriate, no? Maybe I can clean up the error message?

**Comment by robstryker** [comment]
I'm not sure what's changed, but, saving the bad path now works (no error message at all) and now the server errors cleanly on start. 

```
Unable to start the server:  Extension backend error - 
server can not be started: server wildfly 23.x can not find a valid virtual machine to use.
```

I'm going to close this as works-for-me. Yes, I'm aware allowing the user to save random strings isn't great, but, it's not much different than a text editor, so, this is what we have.
