### ISSUE TITLE
Error while processing secure storage

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-server#65]
I finally managed to update rsp-client to handle 0.10.0.
When the password (mypassword) is returned, I noticed the following error:

```
org.jboss.tools.rsp.secure.crypto.CryptoException: Unable to decrypt secure storage
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:65)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.checkKey(SecureStorageGuardian.java:49)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.addClient(SecureStorageGuardian.java:36)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.authenticateClient(SecureStorageGuardian.java:75)
	at org.jboss.tools.rsp.server.model.ServerManagementModel.clientAdded(ServerManagementModel.java:82)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.clientAdded(ServerManagementServerImpl.java:85)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.oneSocket(ServerManagementServerLauncher.java:131)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.access$0(ServerManagementServerLauncher.java:113)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher$ListenOnSocketRunnable.run(ServerManagementServerLauncher.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.jboss.tools.rsp.secure.crypto.CryptoException: Error encrypting/decrypting file
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:118)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.decrypt(CryptoUtils.java:71)
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:55)
	... 13 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2164)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:114)
	... 15 more
org.jboss.tools.rsp.secure.crypto.CryptoException: Unable to decrypt secure storage
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:65)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.checkKey(SecureStorageGuardian.java:49)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.addClient(SecureStorageGuardian.java:36)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.authenticateClient(SecureStorageGuardian.java:75)
	at org.jboss.tools.rsp.server.model.ServerManagementModel.clientAdded(ServerManagementModel.java:82)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.clientAdded(ServerManagementServerImpl.java:85)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.oneSocket(ServerManagementServerLauncher.java:131)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.access$0(ServerManagementServerLauncher.java:113)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher$ListenOnSocketRunnable.run(ServerManagementServerLauncher.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.jboss.tools.rsp.secure.crypto.CryptoException: Error encrypting/decrypting file
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:118)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.decrypt(CryptoUtils.java:71)
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:55)
	... 13 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2164)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:114)
	... 15 more
org.jboss.tools.rsp.secure.crypto.CryptoException: Unable to decrypt secure storage
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:65)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.checkKey(SecureStorageGuardian.java:49)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.addClient(SecureStorageGuardian.java:36)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.authenticateClient(SecureStorageGuardian.java:75)
	at org.jboss.tools.rsp.server.model.ServerManagementModel.clientAdded(ServerManagementModel.java:82)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.clientAdded(ServerManagementServerImpl.java:85)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.oneSocket(ServerManagementServerLauncher.java:131)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.access$0(ServerManagementServerLauncher.java:113)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher$ListenOnSocketRunnable.run(ServerManagementServerLauncher.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.jboss.tools.rsp.secure.crypto.CryptoException: Error encrypting/decrypting file
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:118)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.decrypt(CryptoUtils.java:71)
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:55)
	... 13 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2164)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:114)
	... 15 more
org.jboss.tools.rsp.secure.crypto.CryptoException: Unable to decrypt secure storage
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:65)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.checkKey(SecureStorageGuardian.java:49)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.addClient(SecureStorageGuardian.java:36)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.authenticateClient(SecureStorageGuardian.java:75)
	at org.jboss.tools.rsp.server.model.ServerManagementModel.clientAdded(ServerManagementModel.java:82)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.clientAdded(ServerManagementServerImpl.java:85)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.oneSocket(ServerManagementServerLauncher.java:131)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.access$0(ServerManagementServerLauncher.java:113)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher$ListenOnSocketRunnable.run(ServerManagementServerLauncher.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.jboss.tools.rsp.secure.crypto.CryptoException: Error encrypting/decrypting file
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:118)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.decrypt(CryptoUtils.java:71)
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:55)
	... 13 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2164)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:114)
	... 15 more
org.jboss.tools.rsp.secure.crypto.CryptoException: Unable to decrypt secure storage
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:65)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.checkKey(SecureStorageGuardian.java:49)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.addClient(SecureStorageGuardian.java:36)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.authenticateClient(SecureStorageGuardian.java:75)
	at org.jboss.tools.rsp.server.model.ServerManagementModel.clientAdded(ServerManagementModel.java:82)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.clientAdded(ServerManagementServerImpl.java:85)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.oneSocket(ServerManagementServerLauncher.java:131)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.access$0(ServerManagementServerLauncher.java:113)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher$ListenOnSocketRunnable.run(ServerManagementServerLauncher.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.jboss.tools.rsp.secure.crypto.CryptoException: Error encrypting/decrypting file
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:118)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.decrypt(CryptoUtils.java:71)
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:55)
	... 13 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2164)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:114)
	... 15 more
org.jboss.tools.rsp.secure.crypto.CryptoException: Unable to decrypt secure storage
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:65)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.checkKey(SecureStorageGuardian.java:49)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.addClient(SecureStorageGuardian.java:36)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.authenticateClient(SecureStorageGuardian.java:75)
	at org.jboss.tools.rsp.server.model.ServerManagementModel.clientAdded(ServerManagementModel.java:82)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.clientAdded(ServerManagementServerImpl.java:85)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.oneSocket(ServerManagementServerLauncher.java:131)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.access$0(ServerManagementServerLauncher.java:113)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher$ListenOnSocketRunnable.run(ServerManagementServerLauncher.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.jboss.tools.rsp.secure.crypto.CryptoException: Error encrypting/decrypting file
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:118)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.decrypt(CryptoUtils.java:71)
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:55)
	... 13 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2164)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:114)
	... 15 more
org.jboss.tools.rsp.secure.crypto.CryptoException: Unable to decrypt secure storage
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:65)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.checkKey(SecureStorageGuardian.java:49)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.addClient(SecureStorageGuardian.java:36)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.authenticateClient(SecureStorageGuardian.java:75)
	at org.jboss.tools.rsp.server.model.ServerManagementModel.clientAdded(ServerManagementModel.java:82)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.clientAdded(ServerManagementServerImpl.java:85)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.oneSocket(ServerManagementServerLauncher.java:131)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.access$0(ServerManagementServerLauncher.java:113)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher$ListenOnSocketRunnable.run(ServerManagementServerLauncher.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.jboss.tools.rsp.secure.crypto.CryptoException: Error encrypting/decrypting file
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:118)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.decrypt(CryptoUtils.java:71)
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:55)
	... 13 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2164)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:114)
	... 15 more
org.jboss.tools.rsp.secure.crypto.CryptoException: Unable to decrypt secure storage
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:65)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.checkKey(SecureStorageGuardian.java:49)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.addClient(SecureStorageGuardian.java:36)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.authenticateClient(SecureStorageGuardian.java:75)
	at org.jboss.tools.rsp.server.model.ServerManagementModel.clientAdded(ServerManagementModel.java:82)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.clientAdded(ServerManagementServerImpl.java:85)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.oneSocket(ServerManagementServerLauncher.java:131)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.access$0(ServerManagementServerLauncher.java:113)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher$ListenOnSocketRunnable.run(ServerManagementServerLauncher.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.jboss.tools.rsp.secure.crypto.CryptoException: Error encrypting/decrypting file
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:118)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.decrypt(CryptoUtils.java:71)
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:55)
	... 13 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2164)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:114)
	... 15 more
org.jboss.tools.rsp.secure.crypto.CryptoException: Unable to decrypt secure storage
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:65)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.checkKey(SecureStorageGuardian.java:49)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.addClient(SecureStorageGuardian.java:36)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.authenticateClient(SecureStorageGuardian.java:75)
	at org.jboss.tools.rsp.server.model.ServerManagementModel.clientAdded(ServerManagementModel.java:82)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.clientAdded(ServerManagementServerImpl.java:85)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.oneSocket(ServerManagementServerLauncher.java:131)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.access$0(ServerManagementServerLauncher.java:113)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher$ListenOnSocketRunnable.run(ServerManagementServerLauncher.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.jboss.tools.rsp.secure.crypto.CryptoException: Error encrypting/decrypting file
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:118)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.decrypt(CryptoUtils.java:71)
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:55)
	... 13 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2164)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:114)
	... 15 more
org.jboss.tools.rsp.secure.crypto.CryptoException: Unable to decrypt secure storage
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:65)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.checkKey(SecureStorageGuardian.java:49)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.addClient(SecureStorageGuardian.java:36)
	at org.jboss.tools.rsp.server.secure.SecureStorageGuardian.authenticateClient(SecureStorageGuardian.java:75)
	at org.jboss.tools.rsp.server.model.ServerManagementModel.clientAdded(ServerManagementModel.java:82)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.clientAdded(ServerManagementServerImpl.java:85)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.oneSocket(ServerManagementServerLauncher.java:131)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.access$0(ServerManagementServerLauncher.java:113)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher$ListenOnSocketRunnable.run(ServerManagementServerLauncher.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.jboss.tools.rsp.secure.crypto.CryptoException: Error encrypting/decrypting file
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:118)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.decrypt(CryptoUtils.java:71)
	at org.jboss.tools.rsp.secure.model.RSPSecureStorage.load(RSPSecureStorage.java:55)
	... 13 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2164)
	at org.jboss.tools.rsp.secure.crypto.CryptoUtils.doCrypto(CryptoUtils.java:114)
	... 15 more
Client 127.0.0.1:53576 is connected

```

**Comment by jeffmaury** [comment]
Forget about it, I was using a bad password for an existing secure storage.
