### ISSUE TITLE
Issue with Web Poller when using Java 17

### ISSUE THREAD

**Issue by mseele** [redhat-developer/rsp-server#668]
I use _rsp-server_ with _rsp-server-community_ to run Tomcat servers. My default JAVA_HOME (which VS Code uses) is Java 17. When i start a tomcat via the Servers view, my tomcat starts (and is usable) but is always displayed as _Starting_ and after 1 or 2 minutes (might be a timeout) it stops.

What i see in the "Community Server Connector (stderr)" is the following:

```
Exception in thread "Initialize Server State" java.lang.ExceptionInInitializerError
	at org.apache.felix.framework.URLHandlers.createURLStreamHandler(URLHandlers.java:513)
	at java.base/java.net.URL.getURLStreamHandler(URL.java:1436)
	at java.base/java.net.URL.<init>(URL.java:680)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at org.jboss.tools.rsp.server.spi.model.polling.WebPortPoller.onePing(WebPortPoller.java:39)
	at org.jboss.tools.rsp.server.spi.model.polling.WebPortPoller.onePing(WebPortPoller.java:31)
	at org.jboss.tools.rsp.server.spi.model.polling.AbstractPoller.getCurrentStateSynchronous(AbstractPoller.java:98)
	at org.jboss.tools.rsp.server.spi.model.polling.PollThreadUtils.isServerStarted(PollThreadUtils.java:62)
	at org.jboss.tools.rsp.server.generic.servertype.GenericServerBehavior.discoverServerState(GenericServerBehavior.java:311)
	at org.jboss.tools.rsp.server.model.ServerModel$1.run(ServerModel.java:180)
Caused by: java.lang.RuntimeException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @48eff760
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:104)
	... 11 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @48eff760
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.apache.felix.framework.util.SecureAction.setAccesssible(SecureAction.java:871)
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:79)
	... 11 more

Exception in thread "Web Poller: Web Poller: Tomcat 10" java.lang.NoClassDefFoundError: Could not initialize class org.apache.felix.framework.URLHandlersStreamHandlerProxy
	at org.apache.felix.framework.URLHandlers.createURLStreamHandler(URLHandlers.java:513)
	at java.base/java.net.URL.getURLStreamHandler(URL.java:1436)
	at java.base/java.net.URL.<init>(URL.java:680)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at org.jboss.tools.rsp.server.spi.model.polling.WebPortPoller.onePing(WebPortPoller.java:39)
	at org.jboss.tools.rsp.server.spi.model.polling.WebPortPoller.onePing(WebPortPoller.java:31)
	at org.jboss.tools.rsp.server.spi.model.polling.AbstractPoller.pollerRun(AbstractPoller.java:46)
	at org.jboss.tools.rsp.server.spi.model.polling.AbstractPoller.lambda$1(AbstractPoller.java:40)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

When i change `java.home` to Java 11 (/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home) everythings works ok.

Seems like a bug in felix with Java 17.

**Comment by mseele** [comment]
Maybe it is enough to bump apache felix to latest version?

**Comment by mseele** [comment]
https://github.com/redhat-developer/rsp-server/pull/669 will bump felix to 6.0.5 which has been released in june 2021 (from 6.0.3 which is from early 2019)

**Comment by mseele** [comment]
@robstryker Great to see progress towards java 17 support. Is there any roadmap to see when the next releases are planned?

**Comment by robstryker** [comment]
Hey sorry, was on vacation a bit. As I recall I was mid-way through a release when I took vacation (I released rsp-server but not a new extension to consume it). I'll look into verifying it in the next week and seeing what's next.

**Comment by robstryker** [comment]
@mseele  did the most recent release fix this issue for you?

**Comment by mseele** [comment]
> @mseele  did the most recent release fix this issue for you? 

Yes, works fine with Java 17. Thank you

**Comment by rharri** [comment]
I had a similar issue with Tomcat 10.x and Java 17, with the latest update, all is well now. Thanks.

**Comment by robstryker** [comment]
Thanks guys!
