### ISSUE TITLE
CLI throws NPE when remote RSP is killed

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-server#80]
If CLI is connected to an RSP but then this RSP is killed, issing commands throws NPE.
Ex with `list servers`:

```
java.lang.NullPointerException
	at org.jboss.tools.rsp.client.cli.StandardCommandHandler.processCommand(StandardCommandHandler.java:134)
	at org.jboss.tools.rsp.client.cli.StandardCommandHandler.handleInput(StandardCommandHandler.java:72)
	at org.jboss.tools.rsp.client.cli.ServerManagementCLI$1.run(ServerManagementCLI.java:103)
```

**Comment by robstryker** [comment]
* d79873a - (HEAD -> issue80, mine/issue80) Issue 80 - avoid NPE when remote server shuts down (58 seconds ago) <Rob Stryker>
